# Stage 1: Build using Maven
FROM maven:3.9.9-eclipse-temurin-24-alpine AS builder
WORKDIR /app
COPY . . 
RUN mvn clean package -DskipTests

# Stage 2: Run the JAR using a slim JDK image
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/*.jar ./app.jar
#COPY --from=builder /app/target/user-app-0.0.3-SNAPSHOT.jar app.jar
EXPOSE 8085
ENTRYPOINT [ "java" ]
CMD ["-jar", "app.jar"]