# Dockerfile-Benie

#Stage 1: Build using Maven image
# official OpenJDK base image
FROM maven:3.9.6-eclipse-temurin-17 AS builder

# Set working directory
WORKDIR /app

# Copy build files (Maven/Gradle)
COPY pom.xml ./
COPY src ./src

# Build the app (Maven)
RUN mvn clean package -DskipTests

# Stage 2: Runtime container
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

#Copy the compiled jar from builder stage
COPY --from=builder /app/target/*.jar ./app.jar


EXPOSE 8085

#Run the app
CMD ["java", "-jar", "app.jar"]